### ISSUE TITLE
Add direct link clientId support

### ISSUE THREAD

**Issue by J0ker98** [yzyio/adidas-stock-checker#4]
Would be cool if it would be possible to add the direct link support for the clientId too.

**Comment by bommels** [comment]
Nice idea, will implement this likely next week when I have more time

**Comment by J0ker98** [comment]
Maybe before the 29 ;)

**Comment by bommels** [comment]
Maybe I will fix it tomorrow, I don't think it's that much work to implement :)

**Comment by J0ker98** [comment]
Yeah, should be just a copy & paste from the methods used with the pid/sid

**Comment by J0ker98** [comment]
News about it? ;)

**Comment by bommels** [comment]
totally forgot about this, will update asap :)

**Comment by bommels** [comment]
Fixed in commit 99e67a313438748cd2ae24bbad22e3d27ad17a26
